#!/usr/bin/env python3
"""Generate the Available Tools reference section in README.md.

Parses server.py via AST, groups every @mcp.tool() by category, and
rewrites the README block between the <!-- TOOLS:START --> and
<!-- TOOLS:END --> markers.

Run manually:
    python scripts/gen_tools_reference.py

Or add as a pre-commit hook:
    # .pre-commit-config.yaml
    - repo: local
      hooks:
        - id: gen-tools-reference
          name: Update tools reference in README
          entry: python scripts/gen_tools_reference.py
          language: python
          pass_filenames: false
"""

import ast
import pathlib
import sys
import textwrap

REPO_ROOT = pathlib.Path(__file__).parent.parent
SERVER_PY = REPO_ROOT / "src" / "xlights_mcp" / "server.py"
README = REPO_ROOT / "README.md"

START_MARKER = "<!-- TOOLS:START -->"
END_MARKER = "<!-- TOOLS:END -->"

# Ordered groups: (heading, emoji, [tool_names])
GROUPS = [
    ("Show & Configuration", "🗂️", [
        "list_shows",
        "add_show_folder",
        "switch_show",
    ]),
    ("Sequence Inspection", "🔍", [
        "list_models",
        "list_controllers",
        "list_sequences",
        "inspect_sequence",
        "list_timing_tracks",
        "list_effects",
    ]),
    ("Sequence Editing (offline)", "✏️", [
        "add_effect",
        "update_effect",
        "delete_effect",
    ]),
    ("Live xLights Automation", "⚡", [
        "xlights_status",
        "get_open_sequence",
        "render_frame",
        "render_clip",
        "add_effect_live",
        "clone_model_effects",
        "save_sequence_live",
    ]),
    ("Audio Analysis", "🎵", [
        "analyze_song",
        "get_song_structure",
        "get_beat_map",
        "get_energy_profile",
    ]),
    ("Sequence Generation", "💡", [
        "create_sequence",
        "preview_plan",
    ]),
    ("FPP Integration", "📡", [
        "fpp_status",
        "fpp_upload_sequence",
        "fpp_list_playlists",
        "fpp_start_playlist",
        "fpp_stop",
    ]),
    ("Screenshots", "📸", [
        "xlights_screenshot",
        "xlights_screenshot_region",
        "xlights_list_regions",
        "xlights_navigate_and_screenshot",
        "xlights_list_scenes",
        "xlights_screenshot_floating_panel",
        "xlights_annotate_screenshot",
    ]),
    ("Wiki Management", "📖", [
        "wiki_set_path",
        "wiki_list_pages",
        "wiki_read_page",
        "wiki_write_page",
        "wiki_screenshot_to_image",
        "wiki_status",
        "wiki_commit_push",
        "wiki_pull",
    ]),
]


def _is_tool_decorator(node) -> bool:
    """Return True if `node` is @mcp.tool() or @mcp.tool."""
    if isinstance(node, ast.Attribute) and node.attr == "tool":
        return True
    if (isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr == "tool"):
        return True
    return False


def extract_tools(path: pathlib.Path) -> dict[str, dict]:
    """Return {tool_name: {description, params}} for every @mcp.tool() in path."""
    src = path.read_text(encoding="utf-8")
    tree = ast.parse(src)
    tools = {}

    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef):
            continue
        if not any(_is_tool_decorator(d) for d in node.decorator_list):
            continue

        doc = ast.get_docstring(node) or ""
        # First non-empty line of docstring
        first_line = next((l.strip() for l in doc.splitlines() if l.strip()), "")

        # Collect parameter names (skip self, host, port — low-level plumbing)
        params = []
        for arg in node.args.args:
            if arg.arg not in ("self", "host", "port"):
                params.append(arg.arg)

        tools[node.name] = {"description": first_line, "params": params}

    return tools


def build_section(tools: dict[str, dict]) -> str:
    known = set()
    lines = ["## Available Tools", ""]
    lines.append(
        "_This section is auto-generated by `scripts/gen_tools_reference.py`. "
        "Do not edit by hand._"
    )
    lines.append("")

    for heading, emoji, names in GROUPS:
        group_tools = [(n, tools[n]) for n in names if n in tools]
        if not group_tools:
            continue
        known.update(n for n, _ in group_tools)

        lines.append(f"### {emoji} {heading}")
        lines.append("")
        lines.append("| Tool | Description |")
        lines.append("|------|-------------|")
        for name, info in group_tools:
            desc = info["description"].replace("|", "\\|")
            lines.append(f"| `{name}` | {desc} |")
        lines.append("")

    # Catch any tools not assigned to a group
    ungrouped = [(n, t) for n, t in tools.items() if n not in known]
    if ungrouped:
        lines.append("### 🔧 Other")
        lines.append("")
        lines.append("| Tool | Description |")
        lines.append("|------|-------------|")
        for name, info in ungrouped:
            desc = info["description"].replace("|", "\\|")
            lines.append(f"| `{name}` | {desc} |")
        lines.append("")

    total = len(tools)
    lines.append(f"_Total: {total} tools_")
    lines.append("")
    return "\n".join(lines)


def update_readme(readme: pathlib.Path, section: str) -> bool:
    """Replace the block between TOOLS markers with `section`. Returns True if changed."""
    text = readme.read_text(encoding="utf-8")

    start = text.find(START_MARKER)
    end = text.find(END_MARKER)

    if start == -1 or end == -1:
        print(f"ERROR: markers not found in {readme}", file=sys.stderr)
        print(f"  Add '{START_MARKER}' and '{END_MARKER}' to README.md", file=sys.stderr)
        sys.exit(1)

    new_block = f"{START_MARKER}\n{section}{END_MARKER}"
    new_text = text[:start] + new_block + text[end + len(END_MARKER):]

    if new_text == text:
        return False

    readme.write_text(new_text, encoding="utf-8")
    return True


def main():
    tools = extract_tools(SERVER_PY)
    section = build_section(tools)
    changed = update_readme(README, section)

    if changed:
        print(f"README.md updated — {len(tools)} tools across {len(GROUPS)} groups.")
    else:
        print(f"README.md already up to date ({len(tools)} tools).")


if __name__ == "__main__":
    main()
