"""Generate valid .xsq XML files for xLights."""

from __future__ import annotations

import logging
import xml.etree.ElementTree as ET
from pathlib import Path

from pydantic import BaseModel, Field

from xlights_mcp.xlights.models import LightModel, ShowConfig
from xlights_mcp.xlights.palettes import ColorPalette

logger = logging.getLogger(__name__)


class EffectPlacement(BaseModel):
    """A single effect placed on a model at a specific time."""

    model_name: str
    layer: int = 0
    effect_name: str
    start_time_ms: int
    end_time_ms: int
    settings: dict[str, str] = Field(default_factory=dict)
    palette: ColorPalette | None = None


class TimingTrackLabel(BaseModel):
    """A label in a timing track (phoneme, word, etc.)."""

    label: str
    start_time_ms: int
    end_time_ms: int


class TimingTrack(BaseModel):
    """A timing track (e.g., lyric/phoneme track) for the sequence."""

    name: str
    labels: list[list[TimingTrackLabel]] = Field(default_factory=list)  # one list per layer


class AltAudioTrack(BaseModel):
    """A secondary audio track (e.g. a separated stem) shown in xLights'
    waveform view alongside the main mediaFile."""

    path: str
    shortname: str = ""


class SequenceSpec(BaseModel):
    """Complete specification for generating a sequence."""

    song_title: str = ""
    artist: str = ""
    album: str = ""
    media_file: str = ""
    duration_ms: int = 0
    timing_ms: int = 25  # frame rate in ms (25ms = 40fps)
    palettes: list[ColorPalette] = Field(default_factory=list)
    effects: list[EffectPlacement] = Field(default_factory=list)
    timing_tracks: list[TimingTrack] = Field(default_factory=list)
    alt_audio_tracks: list[AltAudioTrack] = Field(default_factory=list)


def write_xsq(
    spec: SequenceSpec,
    show_config: ShowConfig,
    output_path: Path,
) -> Path:
    """Generate a .xsq file from a sequence specification.

    Args:
        spec: The sequence specification with effects and palettes
        show_config: The show configuration (models, controllers)
        output_path: Where to write the .xsq file

    Returns:
        Path to the written .xsq file
    """
    root = ET.Element("xsequence")
    root.set("BaseChannel", "0")
    root.set("ChanCtrlBasic", "0")
    root.set("ChanCtrlColor", "0")
    root.set("FixedPointTiming", "1")
    root.set("ModelBlending", "true")

    # <head> section
    head = ET.SubElement(root, "head")
    _add_text_elem(head, "version", "2025.13")
    _add_text_elem(head, "author", "")
    _add_text_elem(head, "author-email", "")
    _add_text_elem(head, "author-website", "")
    _add_text_elem(head, "song", spec.song_title)
    _add_text_elem(head, "artist", spec.artist)
    _add_text_elem(head, "album", spec.album)
    _add_text_elem(head, "MusicURL", "")
    _add_text_elem(head, "comment", "Generated by xLights MCP Server")
    _add_text_elem(head, "sequenceTiming", f"{spec.timing_ms} ms")
    _add_text_elem(head, "sequenceType", "Media")
    _add_text_elem(head, "mediaFile", spec.media_file)
    if spec.alt_audio_tracks:
        alt_tracks = ET.SubElement(head, "altAudioTracks")
        for track in spec.alt_audio_tracks:
            track_elem = ET.SubElement(alt_tracks, "track")
            track_elem.set("shortname", track.shortname)
            track_elem.text = track.path
    _add_text_elem(head, "sequenceDuration", f"{spec.duration_ms / 1000:.3f}")
    ET.SubElement(head, "imageDir")

    # <nextid>
    _add_text_elem(root, "nextid", "1")

    # <Jukebox>
    ET.SubElement(root, "Jukebox")

    # <ColorPalettes>
    palettes_elem = ET.SubElement(root, "ColorPalettes")
    palette_index_map: dict[int, int] = {}  # effect index → palette index

    # Build unique palettes
    palette_strings: list[str] = []
    for palette in spec.palettes:
        ps = palette.to_xlights_string()
        if ps not in palette_strings:
            palette_strings.append(ps)

    for ps in palette_strings:
        cp = ET.SubElement(palettes_elem, "ColorPalette")
        cp.text = ps

    # <EffectDB> — deduplicated effect settings
    effect_db_elem = ET.SubElement(root, "EffectDB")
    effect_settings_map: dict[str, int] = {}  # settings string → index

    for eff in spec.effects:
        settings_str = _build_effect_settings(eff)
        if settings_str not in effect_settings_map:
            idx = len(effect_settings_map)
            effect_settings_map[settings_str] = idx
            e = ET.SubElement(effect_db_elem, "Effect")
            e.text = settings_str

    # <DataLayers>
    data_layers = ET.SubElement(root, "DataLayers")
    dl = ET.SubElement(data_layers, "DataLayer")
    dl.set("name", "Nutcracker")
    dl.set("source", "1")

    # <DisplayElements> — list all models in the sequencer
    display_elems = ET.SubElement(root, "DisplayElements")

    # Collect unique model names from effects
    models_used = set()
    for eff in spec.effects:
        models_used.add(eff.model_name)

    # Add all show models (even ones without effects, matching xLights behavior)
    all_model_names = {m.name for m in show_config.models}
    all_names = sorted(all_model_names | models_used)

    for name in all_names:
        de = ET.SubElement(display_elems, "Element")
        de.set("collapsed", "0")
        de.set("type", "model")
        de.set("name", name)
        de.set("visible", "1")
        de.set("active", "0")

    # Add timing tracks (lyric tracks, etc.) to DisplayElements
    for track in spec.timing_tracks:
        de = ET.SubElement(display_elems, "Element")
        de.set("collapsed", "0")
        de.set("type", "timing")
        de.set("name", track.name)
        de.set("visible", "1")
        de.set("active", "0")

    # <ElementEffects> — actual effect placements per model
    element_effects = ET.SubElement(root, "ElementEffects")

    # Group effects by model
    effects_by_model: dict[str, list[EffectPlacement]] = {}
    for eff in spec.effects:
        effects_by_model.setdefault(eff.model_name, []).append(eff)

    for name in all_names:
        ee = ET.SubElement(element_effects, "Element")
        ee.set("type", "model")
        ee.set("name", name)

        model_effects = effects_by_model.get(name, [])

        # Group by layer
        layers: dict[int, list[EffectPlacement]] = {}
        for eff in model_effects:
            layers.setdefault(eff.layer, []).append(eff)

        # Always have at least one layer
        if not layers:
            ET.SubElement(ee, "EffectLayer")
        else:
            for layer_idx in sorted(layers.keys()):
                layer_elem = ET.SubElement(ee, "EffectLayer")
                for eff in sorted(layers[layer_idx], key=lambda e: e.start_time_ms):
                    effect_elem = ET.SubElement(layer_elem, "Effect")
                    effect_elem.set("name", eff.effect_name)
                    effect_elem.set("startTime", str(eff.start_time_ms))
                    effect_elem.set("endTime", str(eff.end_time_ms))

                    # Reference into EffectDB
                    settings_str = _build_effect_settings(eff)
                    if settings_str in effect_settings_map:
                        effect_elem.set("ref", str(effect_settings_map[settings_str]))

                    # Reference palette
                    if eff.palette:
                        ps = eff.palette.to_xlights_string()
                        try:
                            pidx = palette_strings.index(ps)
                            effect_elem.set("palette", str(pidx))
                        except ValueError:
                            pass

    # Add timing tracks to ElementEffects (phoneme labels)
    for track in spec.timing_tracks:
        te = ET.SubElement(element_effects, "Element")
        te.set("type", "timing")
        te.set("name", track.name)

        for layer_labels in track.labels:
            layer_elem = ET.SubElement(te, "EffectLayer")
            for lbl in sorted(layer_labels, key=lambda l: l.start_time_ms):
                label_elem = ET.SubElement(layer_elem, "Effect")
                label_elem.set("label", lbl.label)
                label_elem.set("startTime", str(lbl.start_time_ms))
                label_elem.set("endTime", str(lbl.end_time_ms))

    # <lastView>
    _add_text_elem(root, "lastView", "0")

    # <TimingTags>
    ET.SubElement(root, "TimingTags")

    # Write to file — use double quotes in XML declaration to match xLights format
    tree = ET.ElementTree(root)
    ET.indent(tree, space="  ")

    with open(output_path, "w", encoding="UTF-8") as f:
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
        tree.write(f, encoding="unicode", xml_declaration=False)

    logger.info(f"Wrote sequence to {output_path}")
    return output_path


def _build_effect_settings(eff: EffectPlacement) -> str:
    """Build the effect settings string for the EffectDB."""
    parts = []
    for key, val in sorted(eff.settings.items()):
        parts.append(f"{key}={val}")
    return ",".join(parts)


def _add_text_elem(parent: ET.Element, tag: str, text: str) -> ET.Element:
    """Add a child element with text content."""
    elem = ET.SubElement(parent, tag)
    elem.text = text
    return elem
